# Generated by Django 3.1.1 on 2020-10-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='region',
        ),
        migrations.AddField(
            model_name='articles',
            name='region',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.region', verbose_name='Регион'),
        ),
    ]
