# Generated by Django 3.1.1 on 2020-10-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.region', verbose_name='Регион'),
        ),
    ]
