# Generated by Django 3.1.1 on 2020-10-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201014_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('analytica', 'АНАЛИТИКА'), ('news', 'НОВОСТИ')], default='analytica', max_length=20, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
