# Generated by Django 3.1.1 on 2020-10-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201030_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=500, verbose_name='Описание'),
        ),
    ]
