# Generated by Django 3.1.1 on 2020-11-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20201101_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.IntegerField(default=0, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Архив по годам',
                'verbose_name_plural': 'Архив по годам',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('НОВОСТИ', 'НОВОСТИ'), ('АНАЛИТИКА', 'АНАЛИТИКА')], default='АНАЛИТИКА', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('Активный', 'Активный'), ('Не активнен', 'Не активен')], default='Не активнен', max_length=20, verbose_name='Статус'),
        ),
    ]
