# Generated by Django 3.1.1 on 2020-11-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20201103_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
    ]
