# Generated by Django 3.1.1 on 2020-11-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_year_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='url',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('АНАЛИТИКА', 'АНАЛИТИКА'), ('НОВОСТИ', 'НОВОСТИ')], default='АНАЛИТИКА', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published',
            field=models.DateTimeField(blank=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('Не активнен', 'Не активен'), ('Активный', 'Активный')], default='Не активнен', max_length=20, verbose_name='Статус'),
        ),
    ]
