# Generated by Django 3.1.1 on 2020-12-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20201121_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('Активный', 'Активный'), ('Не активнен', 'Не активен')], default='Не активнен', max_length=20, verbose_name='Статус'),
        ),
    ]
